### ISSUE TITLE
jagddruck and day stages

### ISSUE THREAD

**Issue by ratnanil** [ComputationalMovementAnalysis/ComputationalMovementAnalysisData#4]
@froborg and @pampicloud wrote:

> There is a cleaned data set available in the R package but some attributes are missing. In our data exploration we looked into the day phases (dawn,night,dusk,day...) but this attribute is missing in the new data set.
> In the updated data set there is the "jagddruck". This information is very important for our analysis. We would like to have both, the "jagddruck" and the "day stages".

**Comment by ratnanil** [comment]
> In our data exploration we looked into the day phases (dawn,night,dusk,day...) but this attribute is missing in the new data set

`day` and `moonilumination` is now included in [`wildschwein_BE`](https://computationalmovementanalysis.github.io/ComputationalMovementAnalysisData/reference/wildschwein_BE.html).

> In the updated data set there is the "jagddruck". This information is very important for our analysis. 

This was already included in [`schreck_locations`](https://computationalmovementanalysis.github.io/ComputationalMovementAnalysisData/reference/schreck_locations.html)

**Comment by froborg** [comment]
I installed the package again but still can't see neither `day` nore `moonilumination` in `wildschein_BE`. Any idea why?

**Comment by ratnanil** [comment]
Can you try it again now?

**Comment by froborg** [comment]
I did try again and it is still not there. I even deleted the folder ComputationalMovementAnalysis I found on my computer, downloaded everything again but nonetheless can't see it. Please let me know what I'm doing wrong.

```
> devtools::install_github("ComputationalMovementAnalysis/ComputationalMovementAnalysisData")
Downloading GitHub repo ComputationalMovementAnalysis/ComputationalMovementAnalysisData@HEAD
✓  checking for file ‘/private/var/folders/tf/hzv31v4x42q4_mnw4n8ldhsm0000gn/T/RtmpQR3X7x/remotes118bd13fba18f/ComputationalMovementAnalysis-ComputationalMovementAnalysisData-a1acf97/DESCRIPTION’ ...
─  preparing ‘ComputationalMovementAnalysisData’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ComputationalMovementAnalysisData_0.1.3.tar.gz’
   
* installing *source* package ‘ComputationalMovementAnalysisData’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ComputationalMovementAnalysisData)
> library(ComputationalMovementAnalysisData)
> head(wildschwein_BE)
  TierID TierName CollarID         DatetimeUTC       E       N
1      1     Ueli    12272 2014-05-28 21:01:14 2570390 1204820
2      1     Ueli    12272 2014-05-28 21:15:18 2570389 1204826
3      1     Ueli    12272 2014-05-28 21:30:13 2570391 1204821
4      1     Ueli    12272 2014-05-28 21:45:11 2570388 1204826
5      1     Ueli    12272 2014-05-28 22:00:33 2570388 1204819
6      1     Ueli    12272 2014-05-28 22:15:16 2570384 1204828
```

**Comment by ratnanil** [comment]
I am very sorry for this, the error was on my side. I have now tested it on a different computer and it should work after reinstalling the package, restarting the R-session, and then loading the package. Can you test this?

**Comment by froborg** [comment]
Now it works, thank you!
